/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by terrajet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ImageV2Observation struct {
	DataOrigin *string `json:"dataOrigin,omitempty" tf:"data_origin,omitempty"`

	DiskFormat *string `json:"diskFormat,omitempty" tf:"disk_format,omitempty"`

	File *string `json:"file,omitempty" tf:"file,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	ImageSize *string `json:"imageSize,omitempty" tf:"image_size,omitempty"`

	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`
}

type ImageV2Parameters struct {

	// +kubebuilder:validation:Optional
	CmkID *string `json:"cmkId,omitempty" tf:"cmk_id,omitempty"`

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Optional
	ImageURL *string `json:"imageUrl,omitempty" tf:"image_url,omitempty"`

	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// +kubebuilder:validation:Optional
	IsConfig *bool `json:"isConfig,omitempty" tf:"is_config,omitempty"`

	// +kubebuilder:validation:Optional
	MaxRAM *int64 `json:"maxRam,omitempty" tf:"max_ram,omitempty"`

	// +kubebuilder:validation:Optional
	MinDisk *int64 `json:"minDisk,omitempty" tf:"min_disk,omitempty"`

	// +kubebuilder:validation:Optional
	MinRAM *int64 `json:"minRam,omitempty" tf:"min_ram,omitempty"`

	// +kubebuilder:validation:Optional
	OsVersion *string `json:"osVersion,omitempty" tf:"os_version,omitempty"`

	// +kubebuilder:validation:Optional
	Tags map[string]string `json:"tags,omitempty" tf:"tags,omitempty"`

	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// ImageV2Spec defines the desired state of ImageV2
type ImageV2Spec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ImageV2Parameters `json:"forProvider"`
}

// ImageV2Status defines the observed state of ImageV2.
type ImageV2Status struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ImageV2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// ImageV2 is the Schema for the ImageV2s API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,otcjet}
type ImageV2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ImageV2Spec   `json:"spec"`
	Status            ImageV2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ImageV2List contains a list of ImageV2s
type ImageV2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ImageV2 `json:"items"`
}

// Repository type metadata.
var (
	ImageV2_Kind             = "ImageV2"
	ImageV2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ImageV2_Kind}.String()
	ImageV2_KindAPIVersion   = ImageV2_Kind + "." + CRDGroupVersion.String()
	ImageV2_GroupVersionKind = CRDGroupVersion.WithKind(ImageV2_Kind)
)

func init() {
	SchemeBuilder.Register(&ImageV2{}, &ImageV2List{})
}
