//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddJobsObservation) DeepCopyInto(out *AddJobsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddJobsObservation.
func (in *AddJobsObservation) DeepCopy() *AddJobsObservation {
	if in == nil {
		return nil
	}
	out := new(AddJobsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddJobsParameters) DeepCopyInto(out *AddJobsParameters) {
	*out = *in
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = new(string)
		**out = **in
	}
	if in.FileAction != nil {
		in, out := &in.FileAction, &out.FileAction
		*out = new(string)
		**out = **in
	}
	if in.HiveScriptPath != nil {
		in, out := &in.HiveScriptPath, &out.HiveScriptPath
		*out = new(string)
		**out = **in
	}
	if in.Hql != nil {
		in, out := &in.Hql, &out.Hql
		*out = new(string)
		**out = **in
	}
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = new(string)
		**out = **in
	}
	if in.JarPath != nil {
		in, out := &in.JarPath, &out.JarPath
		*out = new(string)
		**out = **in
	}
	if in.JobLog != nil {
		in, out := &in.JobLog, &out.JobLog
		*out = new(string)
		**out = **in
	}
	if in.JobName != nil {
		in, out := &in.JobName, &out.JobName
		*out = new(string)
		**out = **in
	}
	if in.JobType != nil {
		in, out := &in.JobType, &out.JobType
		*out = new(int64)
		**out = **in
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(string)
		**out = **in
	}
	if in.ShutdownCluster != nil {
		in, out := &in.ShutdownCluster, &out.ShutdownCluster
		*out = new(bool)
		**out = **in
	}
	if in.SubmitJobOnceClusterRun != nil {
		in, out := &in.SubmitJobOnceClusterRun, &out.SubmitJobOnceClusterRun
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddJobsParameters.
func (in *AddJobsParameters) DeepCopy() *AddJobsParameters {
	if in == nil {
		return nil
	}
	out := new(AddJobsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapScriptsObservation) DeepCopyInto(out *BootstrapScriptsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapScriptsObservation.
func (in *BootstrapScriptsObservation) DeepCopy() *BootstrapScriptsObservation {
	if in == nil {
		return nil
	}
	out := new(BootstrapScriptsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapScriptsParameters) DeepCopyInto(out *BootstrapScriptsParameters) {
	*out = *in
	if in.ActiveMaster != nil {
		in, out := &in.ActiveMaster, &out.ActiveMaster
		*out = new(bool)
		**out = **in
	}
	if in.BeforeComponentStart != nil {
		in, out := &in.BeforeComponentStart, &out.BeforeComponentStart
		*out = new(bool)
		**out = **in
	}
	if in.FailAction != nil {
		in, out := &in.FailAction, &out.FailAction
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(string)
		**out = **in
	}
	if in.URI != nil {
		in, out := &in.URI, &out.URI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapScriptsParameters.
func (in *BootstrapScriptsParameters) DeepCopy() *BootstrapScriptsParameters {
	if in == nil {
		return nil
	}
	out := new(BootstrapScriptsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterV1) DeepCopyInto(out *ClusterV1) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterV1.
func (in *ClusterV1) DeepCopy() *ClusterV1 {
	if in == nil {
		return nil
	}
	out := new(ClusterV1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterV1) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterV1List) DeepCopyInto(out *ClusterV1List) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterV1, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterV1List.
func (in *ClusterV1List) DeepCopy() *ClusterV1List {
	if in == nil {
		return nil
	}
	out := new(ClusterV1List)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterV1List) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterV1Observation) DeepCopyInto(out *ClusterV1Observation) {
	*out = *in
	if in.AvailableZoneName != nil {
		in, out := &in.AvailableZoneName, &out.AvailableZoneName
		*out = new(string)
		**out = **in
	}
	if in.ChargingStartTime != nil {
		in, out := &in.ChargingStartTime, &out.ChargingStartTime
		*out = new(string)
		**out = **in
	}
	if in.ClusterID != nil {
		in, out := &in.ClusterID, &out.ClusterID
		*out = new(string)
		**out = **in
	}
	if in.ClusterState != nil {
		in, out := &in.ClusterState, &out.ClusterState
		*out = new(string)
		**out = **in
	}
	if in.CoreNodeProductID != nil {
		in, out := &in.CoreNodeProductID, &out.CoreNodeProductID
		*out = new(string)
		**out = **in
	}
	if in.CoreNodeSpecID != nil {
		in, out := &in.CoreNodeSpecID, &out.CoreNodeSpecID
		*out = new(string)
		**out = **in
	}
	if in.CreateAt != nil {
		in, out := &in.CreateAt, &out.CreateAt
		*out = new(string)
		**out = **in
	}
	if in.DeploymentID != nil {
		in, out := &in.DeploymentID, &out.DeploymentID
		*out = new(string)
		**out = **in
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(string)
		**out = **in
	}
	if in.ErrorInfo != nil {
		in, out := &in.ErrorInfo, &out.ErrorInfo
		*out = new(string)
		**out = **in
	}
	if in.ExternalAlternateIP != nil {
		in, out := &in.ExternalAlternateIP, &out.ExternalAlternateIP
		*out = new(string)
		**out = **in
	}
	if in.ExternalIP != nil {
		in, out := &in.ExternalIP, &out.ExternalIP
		*out = new(string)
		**out = **in
	}
	if in.Fee != nil {
		in, out := &in.Fee, &out.Fee
		*out = new(string)
		**out = **in
	}
	if in.HadoopVersion != nil {
		in, out := &in.HadoopVersion, &out.HadoopVersion
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.InstanceID != nil {
		in, out := &in.InstanceID, &out.InstanceID
		*out = new(string)
		**out = **in
	}
	if in.InternalIP != nil {
		in, out := &in.InternalIP, &out.InternalIP
		*out = new(string)
		**out = **in
	}
	if in.MasterNodeIP != nil {
		in, out := &in.MasterNodeIP, &out.MasterNodeIP
		*out = new(string)
		**out = **in
	}
	if in.MasterNodeProductID != nil {
		in, out := &in.MasterNodeProductID, &out.MasterNodeProductID
		*out = new(string)
		**out = **in
	}
	if in.MasterNodeSpecID != nil {
		in, out := &in.MasterNodeSpecID, &out.MasterNodeSpecID
		*out = new(string)
		**out = **in
	}
	if in.OrderID != nil {
		in, out := &in.OrderID, &out.OrderID
		*out = new(string)
		**out = **in
	}
	if in.PrivateIPFirst != nil {
		in, out := &in.PrivateIPFirst, &out.PrivateIPFirst
		*out = new(string)
		**out = **in
	}
	if in.Remark != nil {
		in, out := &in.Remark, &out.Remark
		*out = new(string)
		**out = **in
	}
	if in.SecurityGroupsID != nil {
		in, out := &in.SecurityGroupsID, &out.SecurityGroupsID
		*out = new(string)
		**out = **in
	}
	if in.SlaveSecurityGroupsID != nil {
		in, out := &in.SlaveSecurityGroupsID, &out.SlaveSecurityGroupsID
		*out = new(string)
		**out = **in
	}
	if in.TenantID != nil {
		in, out := &in.TenantID, &out.TenantID
		*out = new(string)
		**out = **in
	}
	if in.UpdateAt != nil {
		in, out := &in.UpdateAt, &out.UpdateAt
		*out = new(string)
		**out = **in
	}
	if in.Vnc != nil {
		in, out := &in.Vnc, &out.Vnc
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterV1Observation.
func (in *ClusterV1Observation) DeepCopy() *ClusterV1Observation {
	if in == nil {
		return nil
	}
	out := new(ClusterV1Observation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterV1Parameters) DeepCopyInto(out *ClusterV1Parameters) {
	*out = *in
	if in.AddJobs != nil {
		in, out := &in.AddJobs, &out.AddJobs
		*out = make([]AddJobsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AvailableZoneID != nil {
		in, out := &in.AvailableZoneID, &out.AvailableZoneID
		*out = new(string)
		**out = **in
	}
	if in.BillingType != nil {
		in, out := &in.BillingType, &out.BillingType
		*out = new(int64)
		**out = **in
	}
	if in.BootstrapScripts != nil {
		in, out := &in.BootstrapScripts, &out.BootstrapScripts
		*out = make([]BootstrapScriptsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClusterAdminSecret != nil {
		in, out := &in.ClusterAdminSecret, &out.ClusterAdminSecret
		*out = new(string)
		**out = **in
	}
	if in.ClusterName != nil {
		in, out := &in.ClusterName, &out.ClusterName
		*out = new(string)
		**out = **in
	}
	if in.ClusterType != nil {
		in, out := &in.ClusterType, &out.ClusterType
		*out = new(int64)
		**out = **in
	}
	if in.ClusterVersion != nil {
		in, out := &in.ClusterVersion, &out.ClusterVersion
		*out = new(string)
		**out = **in
	}
	if in.ComponentList != nil {
		in, out := &in.ComponentList, &out.ComponentList
		*out = make([]ComponentListParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CoreDataVolumeCount != nil {
		in, out := &in.CoreDataVolumeCount, &out.CoreDataVolumeCount
		*out = new(int64)
		**out = **in
	}
	if in.CoreDataVolumeSize != nil {
		in, out := &in.CoreDataVolumeSize, &out.CoreDataVolumeSize
		*out = new(int64)
		**out = **in
	}
	if in.CoreDataVolumeType != nil {
		in, out := &in.CoreDataVolumeType, &out.CoreDataVolumeType
		*out = new(string)
		**out = **in
	}
	if in.CoreNodeNum != nil {
		in, out := &in.CoreNodeNum, &out.CoreNodeNum
		*out = new(int64)
		**out = **in
	}
	if in.CoreNodeSize != nil {
		in, out := &in.CoreNodeSize, &out.CoreNodeSize
		*out = new(string)
		**out = **in
	}
	if in.LogCollection != nil {
		in, out := &in.LogCollection, &out.LogCollection
		*out = new(int64)
		**out = **in
	}
	if in.MasterDataVolumeCount != nil {
		in, out := &in.MasterDataVolumeCount, &out.MasterDataVolumeCount
		*out = new(int64)
		**out = **in
	}
	if in.MasterDataVolumeSize != nil {
		in, out := &in.MasterDataVolumeSize, &out.MasterDataVolumeSize
		*out = new(int64)
		**out = **in
	}
	if in.MasterDataVolumeType != nil {
		in, out := &in.MasterDataVolumeType, &out.MasterDataVolumeType
		*out = new(string)
		**out = **in
	}
	if in.MasterNodeNum != nil {
		in, out := &in.MasterNodeNum, &out.MasterNodeNum
		*out = new(int64)
		**out = **in
	}
	if in.MasterNodeSize != nil {
		in, out := &in.MasterNodeSize, &out.MasterNodeSize
		*out = new(string)
		**out = **in
	}
	if in.NodePublicCertName != nil {
		in, out := &in.NodePublicCertName, &out.NodePublicCertName
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.SafeMode != nil {
		in, out := &in.SafeMode, &out.SafeMode
		*out = new(int64)
		**out = **in
	}
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
	if in.VolumeSize != nil {
		in, out := &in.VolumeSize, &out.VolumeSize
		*out = new(int64)
		**out = **in
	}
	if in.VolumeType != nil {
		in, out := &in.VolumeType, &out.VolumeType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterV1Parameters.
func (in *ClusterV1Parameters) DeepCopy() *ClusterV1Parameters {
	if in == nil {
		return nil
	}
	out := new(ClusterV1Parameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterV1Spec) DeepCopyInto(out *ClusterV1Spec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterV1Spec.
func (in *ClusterV1Spec) DeepCopy() *ClusterV1Spec {
	if in == nil {
		return nil
	}
	out := new(ClusterV1Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterV1Status) DeepCopyInto(out *ClusterV1Status) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterV1Status.
func (in *ClusterV1Status) DeepCopy() *ClusterV1Status {
	if in == nil {
		return nil
	}
	out := new(ClusterV1Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentListObservation) DeepCopyInto(out *ComponentListObservation) {
	*out = *in
	if in.ComponentDesc != nil {
		in, out := &in.ComponentDesc, &out.ComponentDesc
		*out = new(string)
		**out = **in
	}
	if in.ComponentID != nil {
		in, out := &in.ComponentID, &out.ComponentID
		*out = new(string)
		**out = **in
	}
	if in.ComponentVersion != nil {
		in, out := &in.ComponentVersion, &out.ComponentVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentListObservation.
func (in *ComponentListObservation) DeepCopy() *ComponentListObservation {
	if in == nil {
		return nil
	}
	out := new(ComponentListObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentListParameters) DeepCopyInto(out *ComponentListParameters) {
	*out = *in
	if in.ComponentName != nil {
		in, out := &in.ComponentName, &out.ComponentName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentListParameters.
func (in *ComponentListParameters) DeepCopy() *ComponentListParameters {
	if in == nil {
		return nil
	}
	out := new(ComponentListParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobV1) DeepCopyInto(out *JobV1) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobV1.
func (in *JobV1) DeepCopy() *JobV1 {
	if in == nil {
		return nil
	}
	out := new(JobV1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JobV1) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobV1List) DeepCopyInto(out *JobV1List) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JobV1, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobV1List.
func (in *JobV1List) DeepCopy() *JobV1List {
	if in == nil {
		return nil
	}
	out := new(JobV1List)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JobV1List) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobV1Observation) DeepCopyInto(out *JobV1Observation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.JobState != nil {
		in, out := &in.JobState, &out.JobState
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobV1Observation.
func (in *JobV1Observation) DeepCopy() *JobV1Observation {
	if in == nil {
		return nil
	}
	out := new(JobV1Observation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobV1Parameters) DeepCopyInto(out *JobV1Parameters) {
	*out = *in
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = new(string)
		**out = **in
	}
	if in.ClusterID != nil {
		in, out := &in.ClusterID, &out.ClusterID
		*out = new(string)
		**out = **in
	}
	if in.HiveScriptPath != nil {
		in, out := &in.HiveScriptPath, &out.HiveScriptPath
		*out = new(string)
		**out = **in
	}
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = new(string)
		**out = **in
	}
	if in.IsProtected != nil {
		in, out := &in.IsProtected, &out.IsProtected
		*out = new(bool)
		**out = **in
	}
	if in.IsPublic != nil {
		in, out := &in.IsPublic, &out.IsPublic
		*out = new(bool)
		**out = **in
	}
	if in.JarPath != nil {
		in, out := &in.JarPath, &out.JarPath
		*out = new(string)
		**out = **in
	}
	if in.JobLog != nil {
		in, out := &in.JobLog, &out.JobLog
		*out = new(string)
		**out = **in
	}
	if in.JobName != nil {
		in, out := &in.JobName, &out.JobName
		*out = new(string)
		**out = **in
	}
	if in.JobType != nil {
		in, out := &in.JobType, &out.JobType
		*out = new(int64)
		**out = **in
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobV1Parameters.
func (in *JobV1Parameters) DeepCopy() *JobV1Parameters {
	if in == nil {
		return nil
	}
	out := new(JobV1Parameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobV1Spec) DeepCopyInto(out *JobV1Spec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobV1Spec.
func (in *JobV1Spec) DeepCopy() *JobV1Spec {
	if in == nil {
		return nil
	}
	out := new(JobV1Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobV1Status) DeepCopyInto(out *JobV1Status) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobV1Status.
func (in *JobV1Status) DeepCopy() *JobV1Status {
	if in == nil {
		return nil
	}
	out := new(JobV1Status)
	in.DeepCopyInto(out)
	return out
}
