//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectedInstanceV1) DeepCopyInto(out *ProtectedInstanceV1) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectedInstanceV1.
func (in *ProtectedInstanceV1) DeepCopy() *ProtectedInstanceV1 {
	if in == nil {
		return nil
	}
	out := new(ProtectedInstanceV1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProtectedInstanceV1) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectedInstanceV1List) DeepCopyInto(out *ProtectedInstanceV1List) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProtectedInstanceV1, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectedInstanceV1List.
func (in *ProtectedInstanceV1List) DeepCopy() *ProtectedInstanceV1List {
	if in == nil {
		return nil
	}
	out := new(ProtectedInstanceV1List)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProtectedInstanceV1List) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectedInstanceV1Observation) DeepCopyInto(out *ProtectedInstanceV1Observation) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.PriorityStation != nil {
		in, out := &in.PriorityStation, &out.PriorityStation
		*out = new(string)
		**out = **in
	}
	if in.TargetID != nil {
		in, out := &in.TargetID, &out.TargetID
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectedInstanceV1Observation.
func (in *ProtectedInstanceV1Observation) DeepCopy() *ProtectedInstanceV1Observation {
	if in == nil {
		return nil
	}
	out := new(ProtectedInstanceV1Observation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectedInstanceV1Parameters) DeepCopyInto(out *ProtectedInstanceV1Parameters) {
	*out = *in
	if in.DeleteTargetEIP != nil {
		in, out := &in.DeleteTargetEIP, &out.DeleteTargetEIP
		*out = new(bool)
		**out = **in
	}
	if in.DeleteTargetServer != nil {
		in, out := &in.DeleteTargetServer, &out.DeleteTargetServer
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.GroupID != nil {
		in, out := &in.GroupID, &out.GroupID
		*out = new(string)
		**out = **in
	}
	if in.IPAddress != nil {
		in, out := &in.IPAddress, &out.IPAddress
		*out = new(string)
		**out = **in
	}
	if in.ServerID != nil {
		in, out := &in.ServerID, &out.ServerID
		*out = new(string)
		**out = **in
	}
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectedInstanceV1Parameters.
func (in *ProtectedInstanceV1Parameters) DeepCopy() *ProtectedInstanceV1Parameters {
	if in == nil {
		return nil
	}
	out := new(ProtectedInstanceV1Parameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectedInstanceV1Spec) DeepCopyInto(out *ProtectedInstanceV1Spec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectedInstanceV1Spec.
func (in *ProtectedInstanceV1Spec) DeepCopy() *ProtectedInstanceV1Spec {
	if in == nil {
		return nil
	}
	out := new(ProtectedInstanceV1Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectedInstanceV1Status) DeepCopyInto(out *ProtectedInstanceV1Status) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectedInstanceV1Status.
func (in *ProtectedInstanceV1Status) DeepCopy() *ProtectedInstanceV1Status {
	if in == nil {
		return nil
	}
	out := new(ProtectedInstanceV1Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectiongroupV1) DeepCopyInto(out *ProtectiongroupV1) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectiongroupV1.
func (in *ProtectiongroupV1) DeepCopy() *ProtectiongroupV1 {
	if in == nil {
		return nil
	}
	out := new(ProtectiongroupV1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProtectiongroupV1) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectiongroupV1List) DeepCopyInto(out *ProtectiongroupV1List) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProtectiongroupV1, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectiongroupV1List.
func (in *ProtectiongroupV1List) DeepCopy() *ProtectiongroupV1List {
	if in == nil {
		return nil
	}
	out := new(ProtectiongroupV1List)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProtectiongroupV1List) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectiongroupV1Observation) DeepCopyInto(out *ProtectiongroupV1Observation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectiongroupV1Observation.
func (in *ProtectiongroupV1Observation) DeepCopy() *ProtectiongroupV1Observation {
	if in == nil {
		return nil
	}
	out := new(ProtectiongroupV1Observation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectiongroupV1Parameters) DeepCopyInto(out *ProtectiongroupV1Parameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DomainID != nil {
		in, out := &in.DomainID, &out.DomainID
		*out = new(string)
		**out = **in
	}
	if in.DrType != nil {
		in, out := &in.DrType, &out.DrType
		*out = new(string)
		**out = **in
	}
	if in.SourceAvailabilityZone != nil {
		in, out := &in.SourceAvailabilityZone, &out.SourceAvailabilityZone
		*out = new(string)
		**out = **in
	}
	if in.SourceVPCID != nil {
		in, out := &in.SourceVPCID, &out.SourceVPCID
		*out = new(string)
		**out = **in
	}
	if in.TargetAvailabilityZone != nil {
		in, out := &in.TargetAvailabilityZone, &out.TargetAvailabilityZone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectiongroupV1Parameters.
func (in *ProtectiongroupV1Parameters) DeepCopy() *ProtectiongroupV1Parameters {
	if in == nil {
		return nil
	}
	out := new(ProtectiongroupV1Parameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectiongroupV1Spec) DeepCopyInto(out *ProtectiongroupV1Spec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectiongroupV1Spec.
func (in *ProtectiongroupV1Spec) DeepCopy() *ProtectiongroupV1Spec {
	if in == nil {
		return nil
	}
	out := new(ProtectiongroupV1Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectiongroupV1Status) DeepCopyInto(out *ProtectiongroupV1Status) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectiongroupV1Status.
func (in *ProtectiongroupV1Status) DeepCopy() *ProtectiongroupV1Status {
	if in == nil {
		return nil
	}
	out := new(ProtectiongroupV1Status)
	in.DeepCopyInto(out)
	return out
}
